# Generated by Django 4.0.3 on 2022-04-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('phone_num', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('food', models.BooleanField(default=False)),
                ('diapers', models.BooleanField(default=False)),
                ('sanitary', models.BooleanField(default=False)),
                ('blankets', models.BooleanField(default=False)),
                ('longitude', models.FloatField(default=None, null=True)),
                ('latitude', models.FloatField(default=None, null=True)),
            ],
        ),
    ]
