# Generated by Django 4.0.3 on 2022-04-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altruiSMS', '0003_organization_blankets_organization_diapers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=100)),
                ('event_description', models.EmailField(max_length=254)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('address_one', models.CharField(max_length=100)),
                ('address_two', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=5)),
                ('food', models.BooleanField(default=False)),
                ('diapers', models.BooleanField(default=False)),
                ('sanitary', models.BooleanField(default=False)),
                ('blankets', models.BooleanField(default=False)),
            ],
        ),
    ]
