# Generated by Django 4.0.3 on 2022-04-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altruiSMS', '0004_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
