# Generated by Django 4.0.3 on 2022-04-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altruiSMS', '0006_alter_beneficiary_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='stayable',
            field=models.BooleanField(default=False),
        ),
    ]
