# Generated by Django 4.0.3 on 2022-04-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altruiSMS', '0008_remove_event_end_date_remove_event_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
